spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pic
    username: pic
    password: pic

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
