services:
  db:
    image: postgres:16
    container_name: pic_db
    environment:
      POSTGRES_DB: pic
      POSTGRES_USER: pic
      POSTGRES_PASSWORD: pic
    ports:
      - "5432:5432"
    volumes:
      - pic_pgdata:/var/lib/postgresql/data

volumes:
  pic_pgdata:
